version: '3'

services:
  traefik:
    image: traefik:v2.6
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    volumes:
      - "./traefik.yaml:/etc/traefik/traefik.yaml"
      - "./providers:/etc/traefik/providers"
     - "./acme:/etc/traefik/acme"/
    networks:
      - gateway

networks:
  gateway:
    external: true
