apiVersion: apps/v1
kind: Deployment
metadata:
  name: nb-sample-deployment
  labels:
    app: nb-sample
spec:
  selector:
    matchLabels:
      app: nb-sample
  replicas: 1
  template:
    metadata:
      labels:
        app: nb-sample
    spec:
      containers:
      - name: nb-sample
        image: maltewildt/nb-sample:sample-golang-app
        ports:
          - containerPort: 3001
        env:
          - name: "SERVICE_HOST"
            value: ":3001"
---
apiVersion: v1
kind: Service
metadata:
  name: nb-sample-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 3001
    protocol: TCP
    name: http
  selector:
    app: nb-sample
  externalIPs:
  - 20.113.178.234


    